# Discount settings
discount.initial=50.0
discount.step=5.0
# Price settings
price.per.50kg=500.0
weight.uni.kg=50.0
# File settings
file.read.order.path=src/main/resources/files/orders/discount/discount_day_without_ext
file.write.order.path=src/main/resources/files/orders/discount/discount_orders.txt